// lib.rs — library crate root.
//
// This crate has both a [[bin]] (main.rs) and a [lib] (lib.rs).
// The lib target exists only so integration tests in tests/ can import
// the clustering logic.  The proto types are generated by build.rs into
// OUT_DIR — that path is only valid during a cargo build invocation of
// the *binary* target.
//
// Solution: the lib exposes clustering.rs with a minimal stand-alone
// proto module that re-declares just the structs the clustering
// algorithm needs.  No tonic::include_proto!, no OUT_DIR dependency.

pub mod clustering;

// Minimal hand-written proto types for the lib target.
// The binary (main.rs) uses the real tonic-generated versions.
// These must stay in sync with proto/clustering.proto.
pub mod proto {
    #[derive(Clone, Debug, Default)]
    pub struct CasePoint {
        pub id:           String,
        pub reference_no: String,
        pub lat:          f64,
        pub lng:          f64,
        pub status:       String,
        pub county:       String,
    }

    #[derive(Clone, Debug, Default)]
    pub struct Cluster {
        pub id:           String,
        pub lat:          f64,
        pub lng:          f64,
        pub count:        i32,
        pub active_count: i32,
        pub county:       String,
        pub case_ids:     Vec<String>,
    }

    #[derive(Clone, Debug)]
    pub struct ClusterItem {
        pub item: Option<cluster_item::Item>,
    }

    pub mod cluster_item {
        #[derive(Clone, Debug)]
        pub enum Item {
            Cluster(super::Cluster),
            Point(super::CasePoint),
        }
    }
}